name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: db_food
          POSTGRES_USER: db_food_owner
          POSTGRES_PASSWORD: G9QRtqyu0NJV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://ep-blue-surf-a1nvsrm7.ap-southeast-1.aws.neon.tech/db_food?user=db_food_owner&password=G9QRtqyu0NJV&sslmode=require
          SPRING_DATASOURCE_USERNAME: db_food_owner
          SPRING_DATASOURCE_PASSWORD: G9QRtqyu0NJV

      - name: Run tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://ep-blue-surf-a1nvsrm7.ap-southeast-1.aws.neon.tech/db_food?user=db_food_owner&password=G9QRtqyu0NJV&sslmode=require
          SPRING_DATASOURCE_USERNAME: db_food_owner
          SPRING_DATASOURCE_PASSWORD: G9QRtqyu0NJV

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://ep-blue-surf-a1nvsrm7.ap-southeast-1.aws.neon.tech/db_food?user=db_food_owner&password=G9QRtqyu0NJV&sslmode=require
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: G9QRtqyu0NJV

      - name: Build Docker image
        run: docker build -t food-app/food-app:latest .

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push food-app/food-app:latest
